### ISSUE TITLE
Using deprecated ChatGPT 3.5 Snapshot Model

### ISSUE THREAD

**Issue by new01** [DevEmperor/ChatGPT-WearOS#1]
I'm looking at your ChatActivity.java file and it appears you are pointing to an older version of ChatGPT which will be discontinued. The way you select your version of ChatGPT also isn't futureproof as you will have to respecify a new version number of the model every time it updates. 
```
        ChatCompletionRequest ccr = ChatCompletionRequest.builder()
                .model("gpt-3.5-turbo-0301")
                .messages(chatAdapter.getChatMessages())
                .build();
```
Instead of using "gpt-3.5-turbo-0301" with a version number you can just use "gpt-3.5-turbo" as the API will automatically use the most up to date version of ChatGPT. 

As quoted from the OpenAI API [Documentation](https://platform.openai.com/docs/models/continuous-model-upgrades): 

The following models are the temporary snapshots, we will announce their deprecation dates once updated versions are available. If you want to use the latest model version, **use the standard model names like gpt-4 or gpt-3.5-turbo.**

**Comment by DevEmperor** [comment]
Thanks for your advice, I just received the email from OpenAI about the new update to gpt-3.5-turbo. I have adopted the change and committed it.
