### ISSUE TITLE
Can You please add custom api endpoint support

### ISSUE THREAD

**Issue by AshesHub1** [DevEmperor/ChatGPT-WearOS#2]

**Comment by DevEmperor** [comment]
I'm open to adding this feature, but can you please be more specific about what you mean by "custom api endpoint support"? Or give me an example so I understand what you mean. :)

**Comment by AshesHub1** [comment]
I found a free API thing
ChatGPT API Free Reverse Proxy
You need to join the Discord server to sign up for the API
I tried the API, and it works

https://discord.gg/pawan

**Comment by DevEmperor** [comment]
Your idea is great, I haven't heard about that proxy. I will work on a better settings page and include your feature request. :)

**Comment by AshesHub1** [comment]
Thanks
